[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
PORT = { default = "8000" } 